version: "3.9"

services:
  app:
    build: .
    environment:
      - OCR_URL=http://ocr:8000/scan
    ports:
      - "8080:8080"
    depends_on:
      - ocr
    restart: unless-stopped

  ocr:
    build:
      context: .
      dockerfile: ocr/Dockerfile
    restart: unless-stopped
